name: iamok

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 22 * * *'

jobs:
  iamok:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: iamok!
        env:
          SNO: ${{ secrets.SNO }}
          PASSWD: ${{ secrets.PASSWD }}
          QQ: ${{ secrets.QQ }}
          SMTP_CODE: ${{ secrets.SMTP_CODE }}
        run: python iamok.py
